Controllers/CarrinhoCompraController.cs
using LanchesMac.Models;
using LanchesMac.Repositories.Interfaces;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(ILancheRepository lancheRepository, CarrinhoCompra carrinhoCompra)
        {
            _lancheRepository = lancheRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        public IActionResult Index()
        
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItems();
            _carrinhoCompra.CarrinhoCompraItems = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };
            return View(carrinhoCompraVM);
        }
        public IActionResult AdicionarItemNoCarrinhoCompra(int lancheid)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault(l => l.Id == lancheid);
            if (lancheSelecionado != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(lancheSelecionado);
            }
            return RedirectToAction("Index");
        }
        public IActionResult RemoverItemDoCarrinho(int lancheid)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault(l => l.Id == lancheid);
            if (lancheSelecionado != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(lancheSelecionado);
            }
            return RedirectToAction("Index");   
        }

    }
}

Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/LancheController.cs
using LanchesMac.Models;
using LanchesMac.Repositories.Interfaces;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class LancheController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        private readonly ICategoriaRepository _categoriaRepository;

        public LancheController(ILancheRepository lancheRepository, ICategoriaRepository categoriaRepository)
        {
            _lancheRepository = lancheRepository;
            _categoriaRepository = categoriaRepository;
        }

        public IActionResult Index()
        {
            CategoriaLancheViewModel categoriaLanches = new CategoriaLancheViewModel();

            categoriaLanches.ListaCategorias = _categoriaRepository.Categorias.ToList();
            categoriaLanches.ListaLanche = _lancheRepository.Lanches.ToList();
            return View(categoriaLanches);
        }
        public IActionResult List(string categoria)
        {
            IEnumerable<Lanche> lanches;
            string categoriaAtual = string.Empty;
            if (string.IsNullOrEmpty(categoria))
            {
                lanches = _lancheRepository.Lanches.OrderBy(l => l.Id);
                categoriaAtual = "Todos os lanches";
            }
            else
            {
                lanches = _lancheRepository.Lanches.Where(l => l.Categoria.CategoriaNome.Equals(categoria))
                    .OrderBy(c => c.Nome);
            }
            var lanchesListViewModel = new LancheListViewModel
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            };
            return View(lanchesListViewModel);
        }

        public async Task<ActionResult> CategoriaEscolhida(int id)
        {
            var categoriaEscolhida = _lancheRepository.Lanches.Where(l => l.CategoriaId == id).ToList();
            if (categoriaEscolhida != null)
            {
                return PartialView("_ListaLanches", categoriaEscolhida);
            }
            return View();

        }
        public IActionResult Details(int Id)
        {
            var lanche = _lancheRepository.Lanches.FirstOrDefault(l => l.Id == Id); 
            return View(lanche);
        }
        public ViewResult Search(string searchString)
        {
            IEnumerable<Lanche> lanches;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(searchString))
            {
                lanches = _lancheRepository.Lanches.OrderBy(p => p.Id);
                categoriaAtual = "Todos os lanches";
            }
            else
            {
                lanches = _lancheRepository.Lanches.Where(p => p.Nome.ToLower().Contains(searchString.ToLower()));
                if (lanches.Any())
                {
                    categoriaAtual = "Lanches";
                }
                else
                {
                    categoriaAtual = "Nenhum lanche foi encontrado";
                }
            }
            return View("~/Views/Lanche/List.cshtml", new LancheListViewModel
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            });
        }
    }
}

Views/Shared/_Carousel.cshtml
<style>
    img {
        max-height: 500px !important; 
        width: 100% !important;
        object-fit: contain !important;
    }

    .carousel-control-next-icon, .carousel-control-prev-icon {
        background-color: red !important;
        color: red !important; 
    }

    .carousel-control-next-icon:hover, .carousel-control-next-icon:hover,
    .carousel-control-next-icon:focus, .carousel-control-next-icon:focus {
            background-color: red !important;
            color: red !important;
    }
</style>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">


<section>
    <div class="row">
        <div class="col-md-12 d-flex justify-content-center align-items-center">
            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner" style="max-height: 500px !important; width: 1000px !important">
                    <div class="carousel-item active">
                        <img src="~/images/burguer3.png" class="d-block w-100 img-fluid" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="~/images/cheeseburguer2.png" class="d-block w-100 img-fluid" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="~/images/Salada.png" class="d-block w-100 img-fluid" alt="...">
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Anterior</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Próximo</span>
                </button>
            </div>
        </div>
    </div>
</section>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

Views/Shared/_LanchesResumo.cshtml
@model Lanche;
<style>
    .img-itens {
        object-fit: cover !important;
    }

</style>

@if (Model != null)
{
    <div class="col-sm-4 col-md-4 col-lg-4 menu-item" data-aos="fade-up" data-aos-delay="200">
        <a href="@Model.ImagemUrl" class="glightbox lanche-image d-flex justify-content-center" data-gallery="glightbox-gallery-@Model.Id">
            <img src="@Model.ImagemUrl" class="img-fluid menu-img img-itens" />
        </a>
        @*<p class="d-flex justify-content-center glightbox"><img src="@Model.ImagemUrl" class="img-fluid menu-img" /></p>*@
        <p class="text-white price">Preço: @Model.Preco.ToString("c")</p>
        <h4 class="text-white">Lanche: @Model.Nome</h4>
        <a asp-controller="Lanche" class="text-white" asp-action="Details" asp-route-id="@Model.Id">@Model.Nome</a>
        <p class="text-white ingredientss">Lanche: @Model.DescricaoCurta</p>
        <div>
            <p class="button text-white">
                <a class="btn btn-danger" id="cartButton" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-lancheid="@Model.Id">
                    Adicionar
                </a>
            </p>
        </div>
    </div>
    <!-- Add this just before the closing </body> tag in your layout file -->
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const lightbox = GLightbox({
                selector: '.lanche-image',
                type: 'image' // ajustado para vir somente imagens, algumas estavam sendo renderizadas como video.
            });
        });
    </script>

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LanchesMac</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LanchesMac.styles.css" asp-append-version="true" />

    <!-- Favicons -->
    <link href="~/images/favicon.png" rel="icon">
    <link href="~/images/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="~/css/main.css" rel="stylesheet">
    <style>
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            margin: 0;
        }

        main {
            flex: 1;
            min-height: calc(100vh - 80px); /* Subtrai a altura do footer (80px no exemplo) */
        }

        #footer {
            margin-top: auto;
        }
    </style>
</head>

<body class="bg-dark">
    <header id="header" class="header fixed-top d-flex align-items-center">
        <div class="container d-flex align-items-center justify-content-between">

            <a href="@Url.Action("Index", "Home")" class="logo d-flex align-items-center me-auto me-lg-0">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <!-- <img src="~/images/logo.png" alt=""> -->
                <h1>Bomba Lanches<span>.</span></h1>
            </a>

            <nav id="navbar" class="navbar">
                <ul>
                    @*                    <li><a href="@Url.Action("Index", "Home")">Início</a></li>
                    *@
                    <li><a href="#about">Sobre</a></li>
                    <li><a asp-action="Index" asp-controller="Lanche">Menu</a></li>
                    @*<li><a href="#events">Eventos</a></li>*@

                    @*                    <li><a href="#chefs">Chefs</a></li>
                    *@
                    <li><a href="#gallery">Galeria</a></li>

                    <li class="dropdown">
                        <a href="#"><span class="text-danger">Promoções</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
                        <ul>
                            <li><a href="#menu-breakfast">Café da manhã</a></li>
                            <li class="dropdown">
                                <a href="#"><span class="text-danger">Combos</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
                                <ul>
                                    <li><a href="#">Artesanais</a></li>
                                    <li><a href="#">Sanduíches</a></li>
                                    <li><a href="#">Cachorro quente</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Artesanais</a></li>
                            <li><a href="#">Sanduíches</a></li>
                            <li><a href="#">Cachorro quente</a></li>
                            <li><a href="#">Bebidas</a></li>
                        </ul>
                    </li>
                    <li><a asp-action="Index" asp-controller="Contato">Contato</a></li>
                </ul>
            </nav><!-- .navbar -->
            @*            <a class="btn-book-a-table" href="#menu">Cardápio</a>
            *@
            <div class="m-auto">
                <div class="m-auto container-fluid">
                    <div class="d-flex col-md-12 justify-content-center">
                        <div class="info-item d-inline-flex align-items-center">
                            <i class="icon bi bi-clock flex-shrink-0 horarioFuncionamento"></i>
                            <strong style="margin-right: 10px;">Status: </strong>
                            @{
                                var dayOfWeek = DateTime.Now;
                                TimeSpan now = DateTime.Now.TimeOfDay;
                                DateTime HourOpen = new DateTime(2023, 12, 12, 17, 30, 00);
                                DateTime HourClosed = new DateTime(2023, 12, 12, 23, 55, 00);
                                TimeSpan openTime = HourOpen.TimeOfDay;
                                TimeSpan closeTime = HourClosed.TimeOfDay;
                                var isWeek = "mentira";
                                var isWeekEnd = "mentira";
                                if (dayOfWeek.DayOfWeek.ToString() != "Sunday")
                                {
                                    isWeek = "verdade";
                                }
                                else
                                {
                                    isWeekEnd = "verdade";
                                }
                                if (now >= openTime && now <= closeTime && isWeekEnd == "mentira")
                                {
                                    <strong class="text-success ml-2 d-flex align-itens-center">Aberto</strong>
                                }
                                else
                                {
                                    <strong class="text-danger ml-2 d-flex align-itens-center"> Fechado</strong>
                                }
                            }

                        </div>
                    </div>
                </div>
            </div>
            @await Component.InvokeAsync("CarrinhoCompraResumo")

            <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
            <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

        </div>
    </header><!-- End Header -->
    <div class="container bg-dark">
        <main role="main" class="pb-3 mb-5">
            @RenderBody()
        </main>        
    </div>
    <div class="m">
        <footer id="footer" class="footer text-muted">
            <div class="container">
                <div class="row gy-3">
                    <div class="col-lg-3 col-md-6 d-flex">
                        <i class="bi bi-geo-alt icon"></i>
                        <div>
                            <h4>Endereço</h4>
                            <p>
                                Av. 7 de Setembro, 1449<br />Nossa Sra. das Graças<br>
                                Porto Velho, RO 76804-123<br>
                            </p>
                        </div>

                    </div>

                    <div class="col-lg-3 col-md-6 footer-links d-flex">
                        <i class="bi bi-telephone icon"></i>
                        <div>
                            <h4>Reservas</h4>
                            <p>
                                <strong>Contato:</strong> (69) 99220-3204<br>
                                <strong>Email:</strong> bombalanches203@gmail.com<br>
                            </p>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links d-flex">
                        <i class="bi bi-clock icon"></i>
                        <div>
                            <h4>Horários</h4>
                            <p>
                                <strong>Segunda à Sábado: 17:30AM</strong> - 23:55PM<br>
                                Domingo: Fechado
                            </p>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Redes sociais</h4>
                        <div class="social-links d-flex">
                            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                        </div>
                    </div>

                </div>
            </div>
        </footer>

    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/aos/aos.js"></script>
    <script src="~/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_ListaLanches.cshtml
@model List<Lanche>

@foreach (var lanche in Model)
{
    @await Html.PartialAsync("_LanchesResumo", lanche)
}